mybatis:
  type-aliases-package: com.tidc.api.pojo
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: contestmanager  #服务名
  redis:
    host: localhost
    port: 6379
    #    连接超时时间 毫秒
    timeout: 100
    jedis:
      pool:
        #        连接池最大连接数
        max-active: 10
        #        最小空闲连接数
        min-idle: 5
        #        连接池最大阻塞等待时间 -1表示无线
        max-wait: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 546100
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/match-contest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    #   数据源其他配置
    initialSize: 40
    minIdle: 30
    maxActive: 60
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

server:
  port: 8401
eureka:
  instance:
    prefer-ip-address: true #以ip来注册服务
    instance-id: contestmanager-8401
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
info:
  app.name: match-tidc