spring:
  application:
    name: filemanager  #服务名
server:
  port: 6003
eureka:
  instance:
    prefer-ip-address: true #以ip来注册服务
    instance-id: filemanager-6003
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
info:
  app.name: match-tidc